# https://github.com/lsd-rs/lsd

sorting:
  # Whether to group directories together and where.
  # When "classic" is set, this is set to "none".
  # Possible values: first, last, none
  dir-grouping: first

permission: rwx

blocks:
  - permission
  - user
  - group
  - size
  - git
  - date
  - name
